version: '3'

services:
  file_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: file_db
    volumes:
      - file_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  file_db_data:
  user_db_data:
