"""Added tag to documents

Revision ID: 33864b2e130e
Revises: 233b4f01c34e
Create Date: 2023-05-22 22:01:29.453615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33864b2e130e'
down_revision = '233b4f01c34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
